import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import logo from "./logo.png";
import { HiOutlineHome } from "react-icons/hi2";
import Image from 'next/image';

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Jumystap | Admin",
    description: "Generated by @github.com/aidosgal",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#f9f9f9]`}
            >
                <div
                    className='flex bg-white py-5 items-center border-b border-gray-100'
                >
                    <div className='w-[1400px] mx-auto grid grid-cols-12'>
                        <div className='flex col-span-2'>
                            <Image
                                src={logo}
                                alt="logo"
                                className='w-[170px] h-[50px] object-contain'
                            />
                        </div>
                        <div className='flex items-center col-span-8'>
                            <input
                                type="text"
                                placeholder="Поиск по сайту"
                                className="border border-gray-200 px-5 rounded py-2 bg-[#f9f9f9]"
                            />
                            <div className='ml-auto mr-10 px-10 text-blue-500 cursor-pointer py-2 border border-blue-500 rounded-lg'>
                                Обновить
                            </div>
                        </div>
                        <div className='flex col-span-2'>
                            <div className='flex gap-x-3'>
                                <div 
                                    className='w-[50px] flex items-center justify-center text-lg font-semibold text-white h-[50px] rounded-full bg-blue-500'
                                >
                                    A
                                </div>
                                <div>
                                    <div className='text-xl'>Aidos Galimzhan</div>
                                    <div className='text-sm text-gray-500'>agalimzhan928@gmail.com</div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div className='flex'>
                <div className='w-[1400px] mx-auto grid grid-cols-12'>
                    <div className='col-span-2 pr-4'>
                        <a className='flex items-center gap-x-2 mt-5 bg-white px-5 py-2 rounded-lg border-gray-100 border' href='/'>
                            <HiOutlineHome className='text-2xl' />
                            <div className='text-lg'>Аналитика</div>
                        </a>   
                    </div>
                    <div className='col-span-10'>{children}</div>
                </div>
                </div>
            </body>
        </html>
    );
}
